### PR TITLE
Improve OpenCTI Datasets connector 

### PR DESCRIPTION
**Pull request by SYNchroACK**
* cleanup code
* remove urls from configs
* add `CONFIG_REMOVE_CREATOR` setting to remove creator identity from datasets objects.
* remove useless `entrypoint.sh` file
* generalize `Dockerfile` file, renaming `mitre.py` file to `connector.py`

### CODE REVIEW

**Comment by SamuelHassine** [comment]
Hello @SYNchroACK,

Thanks for this great refactor! But we should keep the URLs of the dataset in the configuration as we've a lot of organizations using OpenCTI in the context of an airgaped environment where datasets are sync / hosted through diode and then URLs may change.

Thanks!

Kind regards,
Samuel

**Comment by SYNchroACK** [comment]
Fixed.

**Comment by SYNchroACK** [comment]
@SamuelHassine done. ready to merge

**Comment by SYNchroACK** [comment]
> done. ready to merge



> Hello @SYNchroACK,
> 
> Thanks for this great refactor! But we should keep the URLs of the dataset in the configuration as we've a lot of organizations using OpenCTI in the context of an airgaped environment where datasets are sync / hosted through diode and then URLs may change.
> 
> Thanks!
> 
> Kind regards, Samuel

@SamuelHassine done. ready to merge

**Pull request merged**
