### PR TITLE
[Connector] Fix bug in WorldWatch report entities crawling

### LINKED ISSUE #3103: [Orange Cyber Defense] Fix bug in WorldWatch report entities crawling
## Description

Fix bug in WorldWatch report entities crawling

### PR DESCRIPTION
**Pull request by cert-orangecyberdefense**
### Related issues

* Fix bug in WorldWatch report entities crawling
https://github.com/OpenCTI-Platform/connectors/issues/3103

### CODE REVIEW

**Comment by Lhorus6** [comment]
Hello Integration,
Our partner detected a bug in the connector he developed and maintains. This PR contains his fix. 
Merge it when you can. 
Thanks in advance

**Comment by romain-filigran** [comment]
Does this PR resolve this issue ? : https://github.com/OpenCTI-Platform/connectors/issues/2940

**Comment by cert-orangecyberdefense** [comment]
> Does this PR resolve this issue ? : #2940

No its another issue.

**Comment by cert-orangecyberdefense** [comment]
Hello, @romain-filigran any news on our PR ?

**Review by helene-nguyen — APPROVED** [review]

**Pull request merged**
