### PR TITLE
[Alienvault, CrowdStrike, Phishunt, ThreatFox, URLHaus] added the ability to set x_opencti_score for select connectors

### PR DESCRIPTION
**Pull request by brett-fitz**
### Proposed changes

* `Alienvault`: Allow the ability to set the default `x_opencti_score` or set it by `main_observable_type`
* `CrowdStrike`: Allow the ability to set the `x_opencti_score` based on the low, medium and high score labels added by CrowdStrike.
* `Phishunt`: Allow the ability to set the default `x_opencti_score` or set it by observable type.
* `ThreatFox`: Allow the ability to set the default `x_opencti_score` or set it by observable type.
* `URLHaus`: Allow the ability to set the default `x_opencti_score`.

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

#2725

### CODE REVIEW

**Comment by brett-fitz** [comment]
Tested CrowdStrike with configurations:

```
      CROWDSTRIKE_INDICATOR_LOW_SCORE: "40"
      CROWDSTRIKE_INDICATOR_LOW_SCORE_LABELS: "MaliciousConfidence/Low"
      CROWDSTRIKE_INDICATOR_MEDIUM_SCORE: "60"
      CROWDSTRIKE_INDICATOR_MEDIUM_SCORE_LABELS: "MaliciousConfidence/Medium"
      CROWDSTRIKE_INDICATOR_HIGH_SCORE: "80"
      CROWDSTRIKE_INDICATOR_HIGH_SCORE_LABELS: "MaliciousConfidence/High"
```
and no environment variables set. Both worked as intended 🎉

**Comment by brett-fitz** [comment]
Tested alienvault with configuration:

```
      - ALIENVAULT_DEFAULT_X_OPENCTI_SCORE=50
      - ALIENVAULT_X_OPENCTI_SCORE_IP=60
      - ALIENVAULT_X_OPENCTI_SCORE_DOMAIN=70
      - ALIENVAULT_X_OPENCTI_SCORE_HOSTNAME=75
      - ALIENVAULT_X_OPENCTI_SCORE_EMAIL=70
      - ALIENVAULT_X_OPENCTI_SCORE_FILE=85
      - ALIENVAULT_X_OPENCTI_SCORE_URL=80
      - ALIENVAULT_X_OPENCTI_SCORE_MUTEX=60
      - ALIENVAULT_X_OPENCTI_SCORE_CRYPTOCURRENCY_WALLET=80
```

and no environment variables set. Both worked as intended 🎉

**Comment by brett-fitz** [comment]
Tested ThreatFox with configuration:

```
THREATFOX_DEFAULT_X_OPENCTI_SCORE: "50"
THREATFOX_X_OPENCTI_SCORE_IP: "60"
THREATFOX_X_OPENCTI_SCORE_DOMAIN: "70"
THREATFOX_X_OPENCTI_SCORE_URL: "75"
THREATFOX_X_OPENCTI_SCORE_HASH: "80"
```

and no environment variables set. Both worked as intended 🎉

**Review by Powlinett — APPROVED** [review]
Manual tests ok for: AlienVault, Crowdstrike, ThreatFox and URLHaus 👍
Not able to test Phishunt as the API doesn't send back any data for now but the code seems right.

**Pull request merged**
