### PR TITLE
[Group-IB Connector] bug fixes, code updates, ttl + Improvements 2623 (rebased)

### PR DESCRIPTION
**Pull request by uTomasAnderson**
[Group-IB Connector] bug fixes, code updates, ttl + [Improvements 2623](https://github.com/OpenCTI-Platform/connectors/issues/2623)

### Proposed changes

* TTL added via valid_from, valid_until parameters
* Intrusion Set support added and now optional
* References names update
* Bug fixes

### Related issues

* https://github.com/OpenCTI-Platform/connectors/issues/2623

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by uTomasAnderson** [comment]
Hello @helene-nguyen @yassine-ouaamou!
Rebased pull request according to issues in https://github.com/OpenCTI-Platform/connectors/pull/2699

**Comment by helene-nguyen** [comment]
Thanks @uTomasAnderson! Could you reformat the changes to allow checks to pass?

**Comment by uTomasAnderson** [comment]
Hello @helene-nguyen 
Not sure why linter rise an error with typing libs. It used in params definition like
# type: (Union[dict, list]) -> List[Tuple[str, str, str]]
Also linter rise an error with local files which are divided with empty line and call them third-party.
But anyway all checks pass right now.

**Review by helene-nguyen — APPROVED** [review]

**Comment by helene-nguyen** [comment]
@uTomasAnderson Thanks! Just one more little thing, could you sign your commits?

**Comment by uTomasAnderson** [comment]
Hello @helene-nguyen!
I have no idea why my key id is not detected and `verified` label is not shown up. The key is added to my profile and commit contains key id. 
Is everything OK right now or should I change anything else?

**Comment by uTomasAnderson** [comment]
Done. Was using a wrong flag.

**Pull request closed without merging**
