### PR TITLE
[Feedly connector] use source name as author

### PR DESCRIPTION
**Pull request by Mathieu4141**
### Proposed changes

* Use the source name as the author
* Fix an issue for the newerThan parameter for feeds that caused some articles to not be ingested

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Review by helene-nguyen — APPROVED** [review]

**Comment by helene-nguyen** [comment]
@Mathieu4141 Could you sign your commits please?

**Comment by Mathieu4141** [comment]
> @Mathieu4141 Could you sign your commits please?

What do you mean?

**Comment by Mathieu4141** [comment]
done @helene-nguyen

**Comment by Mathieu4141** [comment]
@helene-nguyen Is there a blocker for those changes to be approved? :)

**Comment by helene-nguyen** [comment]
@Mathieu4141 sorry for the delay, will be merged 😊

**Pull request merged**
