### PR TITLE
[REVERSINGLABS] Update Spectra Analyze connector

### PR DESCRIPTION
**Pull request by MislavReversingLabs**
### Proposed changes

* updating the existing Spectra Analyze connector
* the connector can now also work on IP address and domain name observables and enrich them

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by helene-nguyen** [comment]
@MislavReversingLabs Following our discussion, you can run 

`isort --profile black .`

For sorting the import properly. The command must be run at the connector root folder.

**Comment by MislavReversingLabs** [comment]
@helene-nguyen
I ran the following in my connector's root folder, just like you said:
```
[.../reversinglabs-spectra-analyze]$ pwd
.../connectors/internal-enrichment/reversinglabs-spectra-analyze
[.../reversinglabs-spectra-analyze]$ isort --profile black .
Fixing .../connectors/internal-enrichment/reversinglabs-spectra-analyze/src/main.py
```
The only thing it changed was adding one blank line after imports but the check is still failing. There is nothing more to sort in my `main.py` file.

**Comment by helene-nguyen** [comment]
@MislavReversingLabs Ok I see, I mean running the command on the connectors folder, where all connectors are.

On the path `.../connectors` and not `.../connectors/internal-enrichment/reversinglabs-spectra-analyze`

**Comment by MislavReversingLabs** [comment]
@helene-nguyen Seems like everything is in order now.

**Review by helene-nguyen — APPROVED** [review]

**Pull request closed without merging**
