### PR TITLE
[import-report] Add support for text/html

### PR DESCRIPTION
**Pull request by 2xyo**
### Proposed changes

* Add support for text/html to the import-report connector

### Related issues

* N/A

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
  - just `text/html` filetype
- [x] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by nor3th** [comment]
Hey @2xyo 

Thanks for the nice addition. Can you please make sure that all libraries are present in the requirements.txt file?
Try removing the virtual environment you are using now, create a new one from scratch, run `pip3 install -r requirements.txt` and then run the connector with `python3 main.py`. My guess is that the beautiful soup library is missing, not sure about any other libs.

Regards,

**Comment by 2xyo** [comment]
> Hey @2xyo
> 
> Thanks for the nice addition. Can you please make sure that all libraries are present in the requirements.txt file? Try removing the virtual environment you are using now, create a new one from scratch, run `pip3 install -r requirements.txt` and then run the connector with `python3 main.py`. My guess is that the beautiful soup library is missing, not sure about any other libs.
> 
> Regards,


`beautifulsoup4` is already present in `requirements.txt` :)  (I was surprised because it doesn't looks used)

https://github.com/OpenCTI-Platform/connectors/blob/master/internal-import-file/import-report/src/requirements.txt#L3

But I still skipped using `black` , I forgot to install the pre-commit 👎

**Comment by nor3th** [comment]
:facepalm: True, totally missed that. Please also fix the conflicts. ;)

Regards,

**Comment by nor3th** [comment]
Thank you very much for your work!!

**Pull request merged**
