### PR TITLE
Fixes to Connectors currently cryptolaemus, malpedia, and Virustotal

### PR DESCRIPTION
**Pull request by asucrews**
Added basic Quota Check To Virustotal connector

### CODE REVIEW

**Comment by asucrews** [comment]
Not sure why ensure_formatting is failing. Please let me know so i can fix

**Comment by asucrews** [comment]
Added missing python package and system packages for cryptolaemus

**Comment by asucrews** [comment]
Addd missing python functions to Malepida

**Comment by smclinden** [comment]
> Not sure why ensure_formatting is failing. Please let me know so i can fix

This says it all:  https://github.com/psf/black

Seems like overkill to block a commit for a formatting issue, but...

**Comment by rhaist** [comment]
As you can see [here](https://github.com/OpenCTI-Platform/connectors/blob/master/.circleci/config.yml#L12-L27) the following two commands should be used to finalize a PR:
```
black .
flake8 --ignore=E,W .
```

**Comment by asucrews** [comment]
Thanksfor the info guy! looks like everything is passing

**Comment by SamuelHassine** [comment]
Thanks a lot for this really useful PR!

**Pull request merged**
