### PR TITLE
[TEMPLATE] create init script

### PR DESCRIPTION
**Pull request by Renizmy**
### Proposed changes
* Create an init script to de-templatize a template connector

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

It might be interesting to automatically add the build steps from the script, but I had no idea how to do it automatically ..

### CODE REVIEW

**Comment by helene-nguyen** [comment]
@Renizmy Thanks a lot for this script, I've tested in local and it works pretty well! 
But in the file, when creating a connector with a dash (-), I got

image

Or

image


Do you think you can add in the script a way to replace into the file from examples below to:

image

image


And same for:

in config.yml.sample
image

in config_variables.py
image

Remove the dash (-) and replace with underscore ( _ ) ? 

image
image

**Comment by Megafredo** [comment]
Hello @Renizmy, thank you for your script, it does the job well and the changes you made following @helene-nguyen suggestion work perfectly. Well done !

However, I found a small bug when using :
`sed: can't read  ../external-import/proofpoint-et/src/external-import_connector/config_variables.py: No such file or directory
`
The problem seems to be that the hyphen "-" in the directory name (`external-import_connector`) has not been converted to an underscore "_" 
To fix this, here's a suggested change `${TYPE}` -> `${TYPE//-/_}` l.134
```bash
sed -i -e "s/$NAME/${NAME//-/_}/g" "$NEW_CONNECTOR_DIR/src/${TYPE//-/_}_connector/config_variables.py"
```

**Comment by Renizmy** [comment]
@Megafredo Nice one !

**Review by Megafredo — APPROVED** [review]
It's ok for me ! ;) thanks for the changes !

**Pull request merged**
