### PR TITLE
[ZeroFox] Document collectors and add software observable to C2Domains collector

### PR DESCRIPTION
**Pull request by DNRRomero**
### Proposed changes

* Add pydocs to intelligence collectors
* Create Observable to C2 domains collector based on sample software
* remove family labels in ransomware collector to avoid redundancy

### Checklist

- [X] I consider the submitted work as finished
- [X] I tested the code for its functionality using different use cases
- [X] I added/update the relevant documentation (either on github or on notion)
- [X] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by helene-nguyen** [comment]
Hello @DNRRomero, could you please format the document and lint ?

**Comment by DNRRomero** [comment]
Hi @helene-nguyen  all issues are in this file `/stream/chronicle/src/chronicle.py` which is unrelated to our code

**Comment by DNRRomero** [comment]
@helene-nguyen, after rebasing chronicle issues were fixed, all checks pass now 👍🏽

**Review by helene-nguyen — APPROVED** [review]

**Comment by helene-nguyen** [comment]
@DNRRomero Changes were approved, could you sign your commit to allow me to merge it ?

**Pull request merged**
