### PR TITLE
[IpInfo] Added extraction of asn data from org field

### PR DESCRIPTION
**Pull request by annoyingapt**
### Proposed changes

* Added elif to extract asn data from org field if using free plan.

### Related issues

* https://github.com/OpenCTI-Platform/connectors/issues/2895

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

Screenshot from free plan
Use ASN name: true
Screenshot 2024-11-05 134832

Use ASN name: false
Screenshot 2024-11-05 134814

### CODE REVIEW

**Review by twi252 — APPROVED** [review]
Works okay here, OpenCTI 6.3.11

**Comment by abdullahdevrel** [comment]
Hey guys, I just wanted to say thank you for bringing our (IPinfo's) data to the OpenCTI platform. Let me know if you need any help or anything.

**Comment by twi252** [comment]
@damians-filigran Hey Damian, was hoping we could have someone from Filigran to review please? Appreciate the help!

**Comment by damians-filigran** [comment]
Hi @twi252, I'm not an approver. I'll forward to someone in @helene-nguyen 's team

**Comment by twi252** [comment]
> Hi @twi252, I'm not an approver. I'll forward to someone in @helene-nguyen 's team

No worries, thanks.

**Review by helene-nguyen — APPROVED** [review]

**Comment by helene-nguyen** [comment]
Good to me, thanks for you contribution @annoyingapt

**Pull request merged**
