### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by aaarghhh**
A docker compose file fix.

### Proposed changes

* Fixed an issue found in the docker-compose file

### Checklist

- [X] I consider the submitted work as finished
- [X] I tested the code for its functionality using different use cases

### CODE REVIEW

**Comment by nor3th** [comment]
Hey @aaarghhh 

Thanks for the PR, but why is the environment variable under " an issue?

Regards

**Comment by aaarghhh** [comment]
Hi, the previous yaml was invalid due the quotes.  The variabile CONNECTOR_NAME was like a string. I know it's a template btw I thought to fix It. 🙂

**Comment by SamuelHassine** [comment]
For me the syntax of the docker compose is correct, double quotes are supported.

@aaarghhh what is your problem exactly?

**Comment by aaarghhh** [comment]
Sorry 🙏, my mistake. 
I close the PR.

**Pull request closed without merging**
