### PR TITLE
[crowdsec] Update internal enrichment connector

### PR DESCRIPTION
**Pull request by julienloizelet**
#### Changed

- Change default recommended name from `crowdsec` to `CrowdSec`
- Change CTI url to the console one
- Skip enrichment if the observable has already been enriched by CrowdSec less than a configurable time ago

#### Added

- Add IPv6-Addr scope support
- Add setting to enable/disable the creation of an Indicator depending on the retrieved CrowdSec's CTI reputation
- Add setting to enable/disable the creation of an Attack Pattern from Mitre techniques
- Add setting to enable/disable the creation of a Vulnerability from CVE
- Add setting to enable/disable the creation of a Sighting related to CrowdSec organization
- Add setting to enable/disable the creation of a Sighting for each targeted country
- Add setting to enable/disable the creation of a Note in observable
- Add label types (`reputation`, `scenario's name`, `scenario's label`, `behavior`, `cve`, `mitre techniques` ) and associated colors
- And settings to enable/disable each label type
- Add setting to store last CrowdSec enrichment date in description
- Add setting to specify a minimum delay between two enrichments

#### Removed

- Remove `CROWDSEC_NAME` and `CROWDSEC_DESCRIPTION` settings

### Related issues

There is no related issue. This is an update of the existing connector to improve enrichment.

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by helene-nguyen** [comment]
@julienloizelet can you please fix linting and formatting? Thanks :)

**Comment by julienloizelet** [comment]
> @julienloizelet can you please fix linting and formatting? Thanks :)

@helene-nguyen : It should be fine now. Thanks

**Comment by helene-nguyen** [comment]
@julienloizelet The test in the CI failed, I don't lnow really why as everything is aligned! We just released the new minor version, could you try to align the branch with master branch and re-push it again?

**Comment by julienloizelet** [comment]
> @julienloizelet The test in the CI failed, I don't lnow really why as everything is aligned! We just released the new minor version, could you try to align the branch with master branch and re-push it again?

@helene-nguyen : I've just rebased and re-pushed the branch. But CI still fails (the error does not appear to be related to the crowdsec connector, but, who knows). Please let me know if I can do something. Thanks

**Comment by helene-nguyen** [comment]
@julienloizelet I think I know why, Python will consider the `tests` folder of google-dns connector as the module to use for your connector. Could you try to change the name of your folder by `crowdsec_tests` ?

**Comment by julienloizelet** [comment]
> @julienloizelet I think I know why, Python will consider the `tests` folder of google-dns connector as the module to use for your connector. Could you try to change the name of your folder by `crowdsec_tests` ?

@helene-nguyen :Thanks for finding this. I ended up moving the tests folder to the src folder (as other connectors do), and all the tests seem to pass now.

**Review by helene-nguyen — APPROVED** [review]

**Pull request merged**
