### PR TITLE
[misp] added config switch to disable tag removal.

### PR DESCRIPTION
**Pull request by 3c7**
This allows to disable the removal of OpenCTI import tags.

### CODE REVIEW

**Comment by SamuelHassine** [comment]
@3c7: could you please solve conflicts and re-submit your pull request?

**Comment by 3c7** [comment]
Check!

**Comment by SamuelHassine** [comment]
@3c7: We really thank you for these first very useful pull requests. We are glad to have you with us as one of the first external contributors to the OpenCTI platform. Be sure that we will continue to enhance this MISP connector, with bi-directional capabilities, parallel import of observables and handle multiples instances. The integration scheduler will be enhanced as well, with integration monitoring, statistics and view in real time of the import statuses.

Thanks again!

**Comment by 3c7** [comment]
@SamuelHassine Thank you for open sourcing this project. Always glad if I can contribute to such projects - even if it's just a small commit.

**Pull request merged**
