### PR TITLE
[Malpedia] Adding variable default_marking, and schedule_unit

### PR DESCRIPTION
**Pull request by Megafredo**
### Proposed changes

* Set a new environment variable to define the `default_marking`.
* Set up scheduler without breaking changes (using `schedule_unit`)
* Added traceback
* Updated Readme and config.yml.sample
* Removed `update_existing_data` usage

### Related issues

* #2460 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by Powlinett** [comment]
In `src/mapledia_services/converter_to_stix.py > line 20`, `default_marking` requires `stix2.TLP_GREEN` and `stix2.TLP_RED` variables too.

**Review by Powlinett — APPROVED** [review]
Works like a charm!

**Comment by gileri** [comment]
Hi  @Megafredo, when starting the connector I get the following error :

```
Traceback (most recent call last):
  File "/opt/opencti-connector-malpedia/main.py", line 10, in <module>
    connector = MalpediaConnector()
                ^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-malpedia/malpedia_connector/malpedia.py", line 48, in __init__
    self.default_marking = self.config.load["malpedia"].get("default_marking", None)
                           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'malpedia'
```

Should we open an issue ? Thanks.

**Comment by Megafredo** [comment]
Hi @gileri, thanks for your feedback, I will open the issue and fix it. ;)

**Pull request merged**
