### PR TITLE
[riskiq] add author for all objects

### PR DESCRIPTION
**Pull request by axelfahy**
### Proposed changes

* Add `RiskIQ` as author of the objects created by the connector. 

### Related issues

N/A

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by bip0008** [comment]
minor suggestion: change the config parameter/variable "password"/RISKIQ_PASSWORD  to "TOKEN" or "KEY" in the RiskIQ connector?

**Comment by axelfahy** [comment]
@bip0008 What is the reason? The authentication is done with a username and a password, isn't it?

**Comment by bip0008** [comment]
@axelfahy I tried with username and password but got error invalid credentails, so I looked at their documentation (see https://api.riskiq.net/api/pt_started.html) and authentication is done with username and api key. The connector worked with username and key so that's why I suggested the change :)

**Comment by axelfahy** [comment]
@bip0008 Ok, I see. I will probably do another PR for this, it's not critical and is a breaking change.

**Pull request merged**
